"""users table

Revision ID: 093e761e2002
Revises: 
Create Date: 2023-05-11 15:15:24.034989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093e761e2002'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users table_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users table_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users table_last_name'), ['last_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users table_last_name'))
        batch_op.drop_index(batch_op.f('ix_users table_first_name'))
        batch_op.drop_index(batch_op.f('ix_users table_email'))

    op.drop_table('users table')
    # ### end Alembic commands ###
